# -*- coding: utf-8 -*-
"""flipkart_product_recommend_system.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1YcnMWdSUaoQn3ffYZT7aoxjIkmhRKdQD
"""

import pandas as pd
import numpy as np

test = pd.read_csv("/test.csv")

test

train = pd.read_csv("/train.csv")

train

#train = train.merge(test, on = 'title')

train

train.head(1)

train = train[['id','title','maincateg','platform']]
train

train.dropna(inplace = True)

train.isnull().sum()

train = train.drop_duplicates()

train.duplicated().sum()

train.iloc[0].title

train['title'] = train['title'].apply(lambda x:x.split())

train

train.iloc[0].title

train['maincateg'] = train['maincateg'].apply(lambda x:x.split())

train

train['platform'] = train['platform'].apply(lambda x:x.split())

train

train['tags'] = train['title']+train['maincateg']+train['platform']
train

train.iloc[0].tags

new_df = train[['id','title','maincateg','platform','tags']]

new_df

new_df.iloc[0].title

new_df['tags'] = new_df['tags'].apply(lambda x:" ".join(x))

new_df['tags']

new_df['title'] = new_df['title'].apply(lambda x:" ".join(x))

new_df['maincateg'] = new_df['maincateg'].apply(lambda x:" ".join(x))

new_df['platform'] = new_df['platform'].apply(lambda x:" ".join(x))

new_df.head()

import nltk

from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

def stem(text):
  y = []
  for i in text.split():
    y.append(ps.stem(i))
  return " ".join(y)

ps.stem('fashionable')

new_df['tags'] = new_df['tags'].apply(stem)

new_df['tags'] = new_df['tags'].apply(lambda x:x.lower())

new_df

from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=5000,stop_words="english")

vectors = cv.fit_transform(new_df['tags']).toarray()

vectors

cv.get_feature_names_out()

from sklearn.metrics.pairwise import cosine_similarity

similarity = cosine_similarity(vectors)

similarity

sorted(list(enumerate(similarity[0])), reverse = True, key = lambda x:x[1])[1:50]

def recommend(product):
  product_index = new_df[new_df['title'] == product].index[0]
  distances = similarity[product_index]
  product_list = sorted(list(enumerate(distances)), reverse = True, key = lambda x:x[1])[1:50]
  for i in product_list:
    print(new_df.iloc[i[0]].title)

recommend('Women Multicolor Flats Sandal')

